name: Build and deploy Node.js app to Azure Web App - backend-demo-419

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    permissions:
      contents: read  # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Check release.zip exists before upload  # Debug step
        run: ls -la release.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This ensures the deploy job waits for the build job
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./backend/  # Correct path where artifact will be extracted

      - name: Unzip artifact for deployment
        run: unzip ./backend/release.zip -d ./backend/  # Unzip to backend folder
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'backend-demo-419'
          slot-name: 'Production'
          package: ./backend/  # Ensure the correct path is used
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CA873F177A1B4A5D8C69432829B1A128 }}
